#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/include/sysnum.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("fstat");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("test_proc");
entry("dev");
entry("readdir");
entry("getcwd");
entry("remove");
entry("trace");
entry("sysinfo");
entry("rename");
entry("sem_open");
entry("sem_wait");
entry("sem_post");
entry("sem_close");
entry("sem_getvalue");
entry("settickets");
entry("getpinfo");
entry("waitpid");
entry("shmcreate");
entry("shmopen");
entry("shmattach");
entry("shmdetach");
entry("shmunlink");
entry("mmap");
entry("munmap");
entry("kill2");
entry("sigaction");
entry("sigreturn");
entry("lseek");
entry("dup2");
entry("getppid");
entry("getuid");
entry("setuid");
entry("getgid");
entry("setgid");
entry("getpgid");
entry("setpgid");
entry("tcgetpgrp");
entry("tcsetpgrp");
entry("pipe2");
entry("mincore");
entry("alarm");
entry("poll");
entry("fcntl");
entry("chmod");
entry("fchmod");
entry("clone");
entry("futex");
entry("exit_group");
entry("halt");
entry("reboot");
entry("socket");
entry("bind");
entry("listen");
entry("accept");
entry("connect");
entry("send");
entry("recv");
entry("netstat");
